### PR TITLE
feat: add svelte support

### PR DESCRIPTION
**Pull request by akadotsh**

### CODE REVIEW

**Comment by cezaraugusto** [comment]
cc @OSpoon given your expertise adding support for Preact and Vue, could you help reviewing this one?

**Comment by OSpoon** [comment]
@akadotsh
This is a great PR. I have found that it seems there is a lack of hot updating capability. Could you please confirm this?

**Comment by akadotsh** [comment]
Thank you for the feedback, @OSpoon. I’ve reviewed the code, and you're right hot updating is not working properly. I’ll work on that and update the PR.

**Comment by OSpoon** [comment]
> Thank you for the feedback, @OSpoon. I’ve reviewed the code, and you're right hot updating is not working properly. I’ll work on that and update the PR.

Here are some options related to hot updates, you can refer to them:
https://github.com/sveltejs/svelte-loader#hot-reload

**Review by cezaraugusto — APPROVED** [review]
this is so cool, thanks @akadotsh for taking the time to make this happen. will be included in the next release, thanks!

**Pull request merged**
