### PR TITLE
Fix content_scripts declaration adding extraneous css

### LINKED ISSUE #213: Manifest `content_scripts` declaration adds extraneous `css` during build
Hey there, my extension was just rejected because it had a `content_scripts.css` field with a hallucinated file in there.

**Input**:

```json
  "content_scripts": [
    {
      "matches": [
        "https://google.com/search*",
        "https://www.google.com/search*",
        "https://google.com/",
        "https://www.google.com/"
      ],
      "js": ["src/content/index.ts"]
    }
  ]
```

**Output**:

```json
  "content_scripts": [
    {
      "matches": [
        "https://google.com/search*",
        "https://www.google.com/search*",
        "https://google.com/",
        "https://www.google.com/"
      ],
      "js": [
        "content_scripts/content-0.js"
      ],
      "css": [
        "content_scripts/content-0.css"
      ]
    }
  ],
```

**Workaround**:

```
jq '.content_scripts |= map_values(del(.css))' manifest.json > tmp.json && mv tmp.json manifest.json
```

### PR DESCRIPTION
**Pull request by cezaraugusto**
Fix #213

### CODE REVIEW

**Comment by wottpal** [comment]
Hey @cezaraugusto, somehow I get a different error when trying to build with this version (which prevents me to test it):

```
~/Developer/wottpal/google-maps-link-extension (main*) » bunx extension --version                                                                                                                                       zoma@dennis-mbp-4
2.0.0-beta.2
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/Developer/wottpal/google-maps-link-extension (main*) » EXTENSION_PUBLIC_PRODUCTION_MODE=true bunx extension build -b chrome                                                                                           zoma@dennis-mbp-4
node:fs:1506
  const result = binding.readdir(
                         ^

Error: ENOENT: no such file or directory, scandir '/Users/zoma/Developer/wottpal/google-maps-link-extension/dist/chrome/content_scripts'
    at Object.readdirSync (node:fs:1506:26)
    at /Users/zoma/Developer/wottpal/google-maps-link-extension/node_modules/extension-develop/dist/module.js:112:32169
    at Array.map (<anonymous>)
    at Ct.applyProdOverrides (/Users/zoma/Developer/wottpal/google-maps-link-extension/node_modules/extension-develop/dist/module.js:112:32043)
    at /Users/zoma/Developer/wottpal/google-maps-link-extension/node_modules/extension-develop/dist/module.js:112:33129
    at Hook.eval [as call] (eval at create (/Users/zoma/Developer/wottpal/google-maps-link-extension/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/zoma/Developer/wottpal/google-maps-link-extension/node_modules/tapable/lib/Hook.js:14:14)
    at /Users/zoma/Developer/wottpal/google-maps-link-extension/node_modules/webpack/lib/Compilation.js:3184:40
    at eval (eval at create (/Users/zoma/Developer/wottpal/google-maps-link-extension/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at fn (/Users/zoma/Developer/wottpal/google-maps-link-extension/node_modules/webpack/lib/Compilation.js:500:9) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/Users/zoma/Developer/wottpal/google-maps-link-extension/dist/chrome/content_scripts'
}

Node.js v20.18.0
```

**Comment by cezaraugusto** [comment]
hey @wottpal thanks for catching up on this. I've send an update just now

**Comment by cezaraugusto** [comment]
@wottpal ready for review!

**Review by wottpal — APPROVED** [review]
Can confirm it's working now and accepted by the store w/o further modification 🫡

**Pull request merged**
