### PR TITLE
Several performance improvements

### PR DESCRIPTION
**Pull request by cezaraugusto**
This is a big bundle of changes to make Extension.js lighter and more performant. 

Also:

Simplified interface:

Screenshot 2024-08-06 at 15 13 20

Single utility dev tools for Extension.js browser support 

Screenshot 2024-08-06 at 15 14 01

### CODE REVIEW

**Comment by cezaraugusto** [comment]
Almost finishing this up but I regressed the Vue and Preact support. @OSpoon can you help me out on this? Vue examples `./examples/content-vue` and `./examples/new-vue` only work in `development` mode and Preact examples `./examples/content-preact` are not working with SWC at all.

**Comment by OSpoon** [comment]
> Almost finishing this up but I regressed the Vue and Preact support. @OSpoon can you help me out on this? Vue examples `./examples/content-vue` and `./examples/new-vue` only work in `development` mode and Preact examples `./examples/content-preact` and `./examples/new-preact` are not working with SWC at all.即将完成这项工作，但我回退了 Vue 和 Preact 的支持。你能帮我解决这个问题吗？Vue 示例 `./examples/content-vue` 和 `./examples/new-vue` 只在 `development` 模式下工作，而 Preact 示例 `./examples/content-preact` 和 `./examples/new-preact` 完全无法与 SWC 兼容。

I'll try to troubleshoot the two phenomena you mentioned as soon as possible.

**Comment by OSpoon** [comment]
> Almost finishing this up but I regressed the Vue and Preact support. @OSpoon can you help me out on this? Vue examples `./examples/content-vue` and `./examples/new-vue` only work in `development` mode and Preact examples `./examples/content-preact` and `./examples/new-preact` are not working with SWC at all.

I created a [repo](https://github.com/OSpoon/vue-webpack/blob/main/vue-webpack-plugin.js) that reproduces the issue where Vue.js only works in development mode. I tried loading vue-loader in the beforeRun and watchRun hooks, which works. I suspect this is related to some internal mechanisms of webpack, but I can't prove it.

Could you please confirm this?

**Comment by OSpoon** [comment]
I run `yarn extension create ./examples/content-preact-1.0 --template=preact-typescript` and the example created looks fine. Could you give me a hint?

I haven't found a way to run the examples directly.

**Comment by OSpoon** [comment]
For the examples ./examples/content-preact, ./examples/content-react, or ./examples/content-vue, have you encountered the following prompt when running the start command?

image

**Comment by cezaraugusto** [comment]
@OSpoon regarding https://github.com/extension-js/extension.js/pull/137#issuecomment-2270311915, that sounds good to me. I'm not sure about the implications honestly but I'd take the risk since it's blocking the merge of this one. Feel free to cherry-pick the changes to this PR or I'll do it later tomorrow no problem.

regarding the browser logs in https://github.com/extension-js/extension.js/pull/137#issuecomment-2270423743, yeah seeing that too. It's likely something related to SWC, which we run twice (for the JsFrameworksPlugin and the tranformer code in ResolverPlugin).

**Comment by cezaraugusto** [comment]
Current items that need attention:

- [Example not working] content-css-module 
- [Example not working] new-less 
- [Example not working] new-sass 
- [Example not working] content-preact **(release blocker)**
- [Example not working] new-preact **(release blocker)**
- [Example not working] content-vue (runs dev, doesn't build) **(release blocker)**
- [Example not working] new-vue (runs dev, doesn't build) **(release blocker)**
- [Example not working] chatgpt (Chrome removed their native sidebar??) 
- [Tests] Needs setup of test coverage
- [Tests] Needs fixing existing tests
- [Browsers] Can't run all browsers at once anymore **(release blocker)**

**Comment by OSpoon** [comment]
hi @cezaraugusto,
Please check if `new-preact`, `content-preact`, `new-less`, and `new-sass` are working correctly.

**Comment by cezaraugusto** [comment]
@OSpoon `new-less` and and `new-sass` are reloading well, but it seems there is something with the resolver plugin that is preventing the `scripting` API from injecting styles into the page using these templates. 

for `new-preact`, `content-preact`, they build properly but still can't reload the page

**Comment by cezaraugusto** [comment]
I'm investigating why the resolver isn't working properly

**Comment by cezaraugusto** [comment]
@OSpoon anything else you want to include in this PR before we merge? I'm OK having a Preact fix in a future release.

**Comment by OSpoon** [comment]
I spent some time looking into why `new-preact` is not reloading the page, but unfortunately, I haven't found the cause yet. The [preact-webpack](https://github.com/OSpoon/preact-webpack/blob/swc-loader/webpack.config.js) repo I created seems to be working fine.

I haven't been involved much in browser extensions and build-related work, so I don't have any good ideas at the moment. If I come up with anything new, I'll let you know right away. 😁

**Comment by cezaraugusto** [comment]
@OSpoon awesome, let's get this one into main

**Pull request merged**
